Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/jammy64"

    # Port forwarding pro SSH
    ubuntu.vm.network "forwarded_port", guest: 22, host: 2202, host_ip: "127.0.0.1"

    # Interní síť s pevnou IP
    ubuntu.vm.network "private_network", ip: "192.168.1.3", virtualbox__intnet: "intnet"

    # Hostname
    ubuntu.vm.hostname = "ubuntu"

    # SSH klíč
    ubuntu.vm.provision "file", source: "id_rsa.pub", destination: "~/.ssh/me.pub"

    # Provisioning – přidání klíče + chmod skriptů
    ubuntu.vm.provision "shell", inline: <<-SHELL
      cat /home/vagrant/.ssh/me.pub >> /home/vagrant/.ssh/authorized_keys
      chmod +x /vagrant/install-zabbix-agent2.sh
      chmod +x /vagrant/configure-zabbix-agent2.sh
    SHELL

    # Spuštění instalačního a konfiguračního skriptu
    ubuntu.vm.provision "shell", path: "install-zabbix-agent2.sh"
    ubuntu.vm.provision "shell", path: "configure-zabbix-agent2.sh"
  end
end